@RSVP_HostAddress = https://localhost:7211

POST {{RSVP_HostAddress}}/api/auth
Content-Type: application/json
Accept: application/json
{
    "username": "admin",
    "password": "admin"
}

###

POST {{RSVP_HostAddress}}/api/user
Content-Type: application/json
Accept: application/json
{
  "username": "admin",
  "password": "admin",
  "role": "admin"
}

###

GET {{RSVP_HostAddress}}/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjE4NDg1OC1mYzVkLTRiYzMtN2IzMS0wOGRlMmIxNzM2OTMiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiNDYyZTViYWYtOGU4ZC00NGMwLTgzNmItYWFjY2M2ZWU2YTY2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI2NjE4NDg1OC1mYzVkLTRiYzMtN2IzMS0wOGRlMmIxNzM2OTMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2Mzk2NDQzMSwiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9.p0GT6Z9RKJNNraVXqrHyUOhwGB0BV4LmLdZgMbJw3XI
Accept: application/json

###

POST {{RSVP_HostAddress}}/api/guest
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiZGQ3NGFlOGQtMDQwNy00ZjU3LThlNDgtZGUzZDNiNmUwZmRjIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2NDI4OTU2NCwiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9.Ks9xyjylEFWAEckfaW0iV7TrBJLDL_0cxSSW5XGMGLY
{
  "fullname": "Test2 Test2"
}

###

GET {{RSVP_HostAddress}}/api/guest
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiZTcwNjRiMDctYzIzMi00YWNiLWE0MjUtMzIzYmY1MzUzNDgzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2NDM1MDI5NCwiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9.zoST8JtUsXnKdhCg1HAAP0LHR5EwFF7lh3tZiM2pL_A

###
POST {{RSVP_HostAddress}}/api/invite
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiZTcwNjRiMDctYzIzMi00YWNiLWE0MjUtMzIzYmY1MzUzNDgzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2NDM1MDI5NCwiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9.zoST8JtUsXnKdhCg1HAAP0LHR5EwFF7lh3tZiM2pL_A
{
  "FamilyName": "Test Fam",
  "InviteUrl": "test-fam"
}
