@RSVP_HostAddress = https://localhost:7211

POST {{RSVP_HostAddress}}/api/auth
Content-Type: application/json
Accept: application/json
{
    "username": "admin",
    "password": "admin"
}

###

POST {{RSVP_HostAddress}}/api/user
Content-Type: application/json
Accept: application/json
{
  "username": "admin",
  "password": "admin",
  "role": "admin"
}

###

GET {{RSVP_HostAddress}}/api/user
Content-Type: application/json
Authorization: Bearer {{@BearerToken}}
Accept: application/json

###

POST {{RSVP_HostAddress}}/api/guest
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiYjNmMjdkNjUtNDZkZS00ZTQwLWJhNTEtMWYwMTA0YTA4OWRkIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2NDQ2Mzg0NSwiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9.H1KCTgcJSSVQODty9SvOKAp9CFeaIjDgyuzxM-4ai0k
{
  "fullname": "Test2 Test2"
}

###

GET {{RSVP_HostAddress}}/api/guest
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiYWY2YWQzOTgtZTlkZC00MDdlLWE3ODEtMDdhZGU1MDAwMzI3IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2NDY3NjcxOSwiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9.Uvk0Me9jjyKTb_g29ZRwP0OAKUd_k0ID-KDSPhSnHUI

###
POST {{RSVP_HostAddress}}/api/invite
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiYjNmMjdkNjUtNDZkZS00ZTQwLWJhNTEtMWYwMTA0YTA4OWRkIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2NDQ2Mzg0NSwiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9.H1KCTgcJSSVQODty9SvOKAp9CFeaIjDgyuzxM-4ai0k
{
  "FamilyName": "Invite no guests test 4",
  "InviteUrl": "invite-no-guest-4",
  "GuestIds": [
    "E70D3BDE-31BD-4830-1AF3-08DE2E0C86DD"
  ]
}
