@RSVP_HostAddress = https://localhost:7211

POST {{RSVP_HostAddress}}/api/auth
Content-Type: application/json
Accept: application/json
{
    "username": "admin",
    "password": "admin"
}

###

POST {{RSVP_HostAddress}}/api/user
Content-Type: application/json
Accept: application/json
{
  "username": "admin",
  "password": "admin",
  "role": "admin"
}

###

GET {{RSVP_HostAddress}}/api/user
Content-Type: application/json
Authorization: Bearer {{@BearerToken}}
Accept: application/json

###

POST {{RSVP_HostAddress}}/api/guest
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{@BearerToken}}
{
  "fullname": "Test2 Test2"
}

###

GET {{RSVP_HostAddress}}/api/guest
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiMmUzODMxMDItNmY4OS00Y2Y1LTllM2YtYTIzOWNmMDI0YzdhIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2NDM3OTI4MywiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9._bboPQLL2ufp-kdZ9zm6c-40ooiq0G6a-Wy-MvxniKo

###
POST {{RSVP_HostAddress}}/api/invite
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwianRpIjoiMmUzODMxMDItNmY4OS00Y2Y1LTllM2YtYTIzOWNmMDI0YzdhIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJjZmJjMjMwOS1iZTkzLTQ2MWUtZDI4Ni0wOGRlMmRiYzBmZTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc2NDM3OTI4MywiaXNzIjoiUnN2cCIsImF1ZCI6IlJzdnBVc2VycyJ9._bboPQLL2ufp-kdZ9zm6c-40ooiq0G6a-Wy-MvxniKo
{
  "FamilyName": "Bulk Test",
  "InviteUrl": "bulk-test",
  "Guests": [
    { "FullName" : "Testing 1", "IsAttending" : false},
    { "FullName" : "Testing 2", "IsAttending" : true}
  ]
}
